name: AWS Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/nx-cloud/portal
            git fetch origin main
            git reset --hard origin/main
            npm install
            npx prisma generate
            npm run build
            # Reinicia o processo (Se estiver usando PM2)
            pm2 restart nx-cloud || npm run dev & 
