name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Usando o container oficial do devkitPro
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # Atualiza as bases de dados primeiro
        dkp-pacman -Syu --noconfirm
        
        # Instala o grupo de desenvolvimento do Switch e bibliotecas específicas
        # O switch-dev já contém a libnx
        dkp-pacman -S --noconfirm switch-dev switch-curl switch-mesa switch-glm

    - name: Build
      run: |
        # Em vez de ./configure, use o make diretamente
        make
