name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Usando o container oficial do devkitPro
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dkp-pacman -Syu --noconfirm
        # Adicione aqui outras libs que seu projeto usa (ex: switch-curl, switch-libjson-c)
        dkp-pacman -S --noconfirm switch-libnx switch-curl switch-mesa switch-glm

    - name: Build
      run: |
        # Em vez de ./configure, use o make diretamente
        make
